// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnomrfjpwcglqihvjuda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhub21yZmpwd2NnbHFpaHZqdWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwODY2ODgsImV4cCI6MjA3ODY2MjY4OH0.gIC2g7EdKMQKvA6NXJqzT_A0klIA8HVrUvTACxuSE-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});